### ISSUE TITLE
Could not detect buildpack following instructions

### ISSUE THREAD

**Issue by Tonkpils** [heroku/heroku-buildpack-testrunner#11]
I am unable to get the test runner working on Heroku. I have created a repo out of my buildpack with the testrunner buildpack as the buildpack but Heroku seems to be unable to fetch/detect the build pack.

Am I missing anything here?

```sh
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Fetching set buildpack https://github.com/heroku/heroku-buildpack-testrunner
remote:  !     could not detect buildpack https://github.com/heroku/heroku-buildpack-testrunner
remote:
remote:  !     Push failed
remote: Verifying deploy....
remote:
remote: !	Push rejected to shrouded-depths-81860.
remote:
```

**Comment by jkutner** [comment]
This buildpack requires that the following directories/files exist:

* bin/detect
* bin/release
* bin/compile
* test/

You can see this here:
https://github.com/heroku/heroku-buildpack-testrunner/blob/master/bin/detect#L6

I'll update the docs to make this clear

**Comment by Tonkpils** [comment]
I noticed that from the `detect` file in this repo. I should've checked that first. If you'd like I can make a PR 👍

**Comment by jkutner** [comment]
Yea, a PR would be nice. otherwise i'll get to it shortly

**Comment by bobbytables** [comment]
I thought `release` was an optional file?

**Comment by jkutner** [comment]
@bobbytables yea true. we can remove that from detect.
