### ISSUE TITLE
Example buildpack to be tested?

### ISSUE THREAD

**Issue by otiai10** [heroku/heroku-buildpack-testrunner#16]
I'm trying to test my buildpack by this `heroku-buildpack-testrunner`, it seems helpful a lot.

Should I add **MY** buildpack to the app which is created with **YOUR** buildpack?

Or, do you have any example buildpack which is tested by `heroku-buildpack-testrunner`?

Any comments appreciated. Thank you.

**Comment by jkutner** [comment]
You should run this buildpack (heroku-buildpack-testrunner) on your buildpack's code. If doing this on Heroku it would look like:

```
$ cd my-heroku-buildpack
$ heroku create --buildpack https://github.com/heroku/heroku-buildpack-testrunner
$ git push heroku master
```

For an example, see the [Java buildpack](https://github.com/heroku/heroku-buildpack-java/tree/master/test)

**Comment by otiai10** [comment]
Thank you! I have my project working well.

I was understanding **my** buildpack is loaded automatically somehow. In fact, however, I have to exec `detect`/`compile`/`release` in my test scripts by myself.

Is my understanding right? I really appreciate your comment!

**Comment by jkutner** [comment]
Yea, that sounds right
